### ISSUE TITLE
Numeric planners

### ISSUE THREAD

**Issue by tomitrescak** [AI-Planning/planutils#48]
Hello, does any of these planners do numeric planning? I checked downward and related and they do not.

**Comment by haz** [comment]
@tomitrescak That answer your question? If so, please close this one out, and thanks for your interest!

**Comment by haz** [comment]
I think, given the range of planners we have in there now, this should be handled. @tomitrescak : do let us know if there's one missing that you'd like to see. For the record, this is the current listing:

```
Available:
  hpddl2pddl: HTNTranslate: Translate HPDDL to PDDL
  enhsp-2019: ENHSP (2019)
  forbiditerative-topk: Forbid-Iterative top-k planner
  lama: LAMA
  enhsp: ENHSP
  lama-first: LAMA-FIRST
  downward: Fast Downward
  forbiditerative-diverse-sat: Forbid-Iterative diverse satisficing planner
  cerberus-agl: Cerberus planner for agile planning
  cerberus: Cerberus planners for satisficing and agile planning
  enhsp-2018: ENHSP (2018)
  enhsp-2020: ENHSP (2020)
  val: VAL
  forbiditerative-topq: Forbid-Iterative unordered top-q planner
  kstar: K* planner for the top-k planning problem
  smtplan: SMTPlan+
  optic: The OPTIC temporal planner
  tarski: Tarski
  planning.domains: Planning.Domains API
  forbiditerative: Forbid-Iterative (FI) Planner is an Automated PDDL based planner suite that includes planners for top-k, top-quality, and diverse computational tasks
  cerberus-sat: Cerberus planner for satisficing planning
  forbiditerative-diverse-agl: Forbid-Iterative diverse agile planner
  pyperplan: Pyperplan
  delfi: Delfi1 cost-optimal planner, winner of IPC2018
  tfd: The TFD temporal planner
```
